---
title: "20250801_abner_emmeans.Rmd"
output: pdf_document
date: "2025-08-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(MASS)
library(emmeans)
library(tidyverse)
library(sjPlot)
library(cowplot)

#load local metadata
nsd_yes_metadata <- read_csv("~/Documents/Schloss/Colovas_Data_Accessibility/Data/final/nsd_yes_metadata.csv.gz")

#filter out NAs (important later)
my_data <- nsd_yes_metadata %>%
  filter(., age.in.months != "NA" & da_factor != "NA" & container.title != "NA") %>% 
  mutate(da_factor = factor(da_factor), 
         container.title = factor(container.title))
```

```{r}

# First, fit your model and store it
model <- glm.nb(
    is.referenced.by.count ~ da_factor + log(age.in.months) + container.title +
        container.title*da_factor + log(age.in.months)*da_factor +
        container.title*log(age.in.months) +
        log(age.in.months) * da_factor * container.title,
    data = my_data,
    link = "log"
)
# Define the age values you want to examine (in months)
age_values <- c(12, 36, 60, 120)  # Adjust these as needed
# Get emmeans on the link scale for all combinations
emm <- emmeans(model,  ~ da_factor + age.in.months | container.title,
        at = list(age.in.months = age_values), CIs = TRUE,
        type = "response")
# Get pairwise comparisons (differences) between da_factor levels
differences <- contrast(
    emm, by = c("age.in.months", "container.title"),
    method = "revpairwise",
    ratios = TRUE, CIs = TRUE
)
# See the contrasts
summary(differences)
# Plot the contrasts
plot(differences, ratios = TRUE)


# # working on plotting better
ratio_data <-  tibble(emmip(differences, ~ age.in.months | container.title, CIs = TRUE, plotit = FALSE))

ratio_data %>%  
  filter(container.title != "Journal of Microbiology &amp; Biology Education") %>%  
ggplot(ratio_data, mapping = aes(x = xvar, y = yvar)) + 
  geom_point() + 
  geom_linerange(aes(ymin = LCL, ymax = UCL)) + 
  facet_wrap(vars(container.title), scales = "free_y", 
             labeller = label_wrap_gen(width = 20))  + 
  labs(title = "Ratio of daYes/daNo over time with 95% CI from emmip", 
       x = "Age in Months(factor)", 
       y = "Ratio of daYes/daNo")
  

```

## Create Plot from Abner

-   "Also, I think this result would be even clearer if you made a plot
    with "age" in the horizontal axis, "predicted citations" in the
    vertical axis, and lines colored by "da_factor"." - AHB
-   These plots are each made with a different glm.nb model (one for
    each journal), which is why they are not combined into a faceted plot.

```{r}
#smaller model with 2 terms
two_term_glmnb <-function(model_data, model_name) {

  total_model <-MASS::glm.nb(is.referenced.by.count~ da_factor + log(age.in.months) + 
       + log(age.in.months)*da_factor + log(age.in.months)*da_factor, data = model_data, link = log)

  return(total_model)
 
}

journals <- 
  nsd_yes_metadata %>%  
  count(journal_abrev) %>%  
  filter(journal_abrev != "jmbe") 

j <- 3

for(j in 1:nrow(journals)) { 
  journal_data <- 
  nsd_yes_metadata %>% 
    filter(journal_abrev == journals[[j,1]]) %>%  
    mutate(da_factor = factor(da))


  model <- two_term_glmnb(journal_data, journals[[j,1]])



  
  if(j == 3) { #genomea = 5
  p <-  get_model_data(model = model, type = "pred", terms = c("da_factor", "age.in.months[84,120,144]"))
  }
  else if (j == 9) { ##Mra - 7 
    p <-  get_model_data(model = model, type = "pred", terms = c("da_factor", "age.in.months[12,60,84]"))
    
  }
  else if (j == 10 | j == 11 ) { #msphere, msystems 9 years
  p <-  get_model_data(model = model, type = "pred", terms = c("da_factor", "age.in.months[12,60,84,108]"))
  }
  else if (j == 12 ) { 
    p <-  get_model_data(model = model, type = "pred", terms = c("da_factor", "age.in.months[12,60,84,120]"))
  }
  else { 
     p <-  get_model_data(model = model, type = "pred", terms = c("da_factor", "age.in.months[12,60,84,120,180]"))
  }
  
 model_graph <-  
   p %>%  
   tibble(da_factor = ifelse(.$x == 1, "Data not available", "Data available"), predicted_citations = .$predicted, age.in.months = .$group) %>%  
  ggplot(mapping = aes(x = age.in.months, y = predicted_citations, 
                                color = da_factor)) + 
   geom_point() + 
   geom_linerange(aes(ymin = conf.low,
                    ymax = conf.high)) +
   geom_path(aes(x = age.in.months, y = predicted_citations, group = da_factor)) +
   labs(title = paste0("Predicted Number of citations for ", journals[[j,1]], "\nusing two term fixed GLM"),  
        x = "Age in Months", 
        y = "Predicted Number Citations", 
        color = "Data availability with 95% CI")
   
 assign(paste0(journals[[j,1]], "_plot"), model_graph)
 print(model_graph)
  
}


# plot_names <-  
# journals %>%  
#   mutate(plot_name = paste0(journal_abrev, "_plot")) %>% 
#   select(plot_name)
#   
# 
# plot_grid(plotlist = mget(paste0(journals$journal_abrev,"_plot")))


```

