datasets: 
  groundtruth: Data/groundtruth.csv
  gt_subset_30: Data/gt_subset_30.csv
  
ml_variables: 
  new_seq_data
  availability
  
method: 
  glmnet
  rf
  rpart2
  xgbTree
  
nseeds: 10
ncores: 16

