name: data_acc
channels:
  - bioconda
  - r
  - conda-forge
  - defaults
dependencies:
  - snakemake=7.32.4
  - r-base=4.3.3
  - r-tidyverse
  - r-tidytext
  - r-rcrossref
  - r-mikropml
  - r-tm
  - r-rvest
  - r-jsonlite
  - r-tokenizers
  - r-httr2
  - r-xml2
  - r-textstem
  - r-cowplot
  - r-devtools
  - r-randomforest
  - r-microbenchmark
  - r-quarto
  - r-rscopus
  - r-rentrez
  - r-caret
  - r-rlang


  


