name: data_acc
channels:
  - bioconda
  - r
  - conda-forge
  - defaults
dependencies:
  - snakemake=7.32.4
  - r-base
  - r-tidyverse
  - r-tidytext
  - r-rcrossref
  - r-mikropml
  - r-tm
  - r-rvest
  - r-jsonlite
  - r-tokenizers
  - r-httr2


