---
title: "Linkrot Paper"
author: "Joanna Colovas"
format: pdf
editor: visual
---


-   Abstract
-   Importance
    -   Investigate the number of links that are still viable in published scientific papers
    -   Why do we care? 
        -   We want people to be able to access resources in perpetuity
        -   Reproducible research aims 
        -   Access to datasets
            -   "By providing persistent
 links to the underlying data, methods, code, and derivative products, the paper
 becomes more transparent." - from Pat's ORI narrative 
    -   A lot of large datasets/code are available at links as well as code, and we want that to be accessible 
        -   NCBI datasets
        -   Github repositories

-   Keywords
    -   Data accessibility
    -   Data reproducibility
-   Introduction
    -   Data availbility status/current availability and reproducibility guidelines
    -   Why make data available?
    -   How does this contribute to data availability?
    

-   Results
    -   Table of findings x# of links from x# of papers
        -   Number of links that are still alive
        -   What kind of errors we have for the links in each paper
        -   Average number of links/paper
        -   Does this change by journal? 
    -   Some graphs describing further the number of links in any given category 
    

-   Discussion
    -   How do we make things more accessible 
    -   Ways to keep links from going rotten
    -   Can you submit a new link to a journal? 
    -   Or some kind of redirect from the orginal link if it's gone rotten
    -   How often should you check your links to make sure they're NOT rotten
-   Materials and Methods
-   Supplemental Material file list (where applicable)
-   Acknowledgelments
-   References

-   Questions to answer: 
    -   How to set up this repo on github? Should it be separate from the DA repo? 
    -   If it's separate, do we still show the stuff to get the dataset, or do we just make the dataset available?
    -   Do we have questions abou thow the linkrot affects the amount of citations on a paper? If yes, than this goes with DA more closely.