# cluster commands
cluster:
    sbatch
        --job-name={rule}-{wildcards}
        --account={resources.account}
        --partition={resources.partition}
        --mail-user={resources.email}
        --nodes=1
        --ntasks=1
        --cpus-per-task={threads}
        --mem-per-cpu={resources.mem_mb}MB
        --time={resources.time}
        --output=log/hpc/jobs/{rule}/{rule}.{wildcards}.out
default-resources:
  - account=pschloss99
  - partition=standard
  - email=jocolova@med.umich.edu
  - mem_mb=512
  - time="24:00:00"
conda-frontend: "mamba"
immediate-submit: False
jobs: 4999
keep-going: true
latency-wait: 120
max-jobs-per-second: 100
max-status-checks-per-second: 100
notemp: true
printshellcmds: true
scheduler: greedy
use-conda: true
verbose: true