# cluster commands
cluster:
    mkdir -p log/hpc/jobs/{rule}/ && 
    sbatch --job-name={rule}
        --account=pschloss99
        --partition=largemem,standard
        --mail-user=jocolova@med.umich.edu
        --nodes=1
        -c1
        --mem={resources.mem_mb}
        --time={resources.time}
        --output=log/hpc/jobs/{rule}/{rule}.out
default-resources:
  - cpus=1
  - mem_mb=20000
  - time="48:00:00"
  - job_name="data"
conda-frontend: "mamba"
immediate-submit: False
jobs: 4999
keep-going: true
latency-wait: 120
max-jobs-per-second: 100
max-status-checks-per-second: 100
notemp: true
printshellcmds: true
scheduler: greedy
use-conda: true
verbose: true

group-components:
  - get_doi=1
  - get_html=1
  - crossref=6
  - wos = 12
