# cluster commands
cluster:
    mkdir -p log/hpc/jobs/{rule}/ && 
    sbatch --job-name={rule}
        --account=pschloss99
        --partition=standard
        --mail-user=jocolova@med.umich.edu
        --nodes=1
        --cpus-per-task={resources.cpus}
        --mem={resources.mem_mb}
        --time={resources.time}
        --output=log/hpc/jobs/{rule}/{rule}.out
default-resources:
  - cpus=1
  - mem_mb=10000
  - time="24:00:00"
  - job_name="data"
conda-frontend: "mamba"
immediate-submit: False
jobs: 4999
keep-going: true
latency-wait: 120
max-jobs-per-second: 100
max-status-checks-per-second: 100
notemp: true
printshellcmds: true
scheduler: greedy
use-conda: true
verbose: true